{
  "permissions": {
    "allow": [
      "Bash(git -C {REPO_PATH} pull*)",
      "Bash(git -C {REPO_PATH} fetch*)",
      "Bash(git -C {REPO_PATH} log*)",
      "Bash(git -C {REPO_PATH} rev-parse*)",
      "Bash(git -C {REPO_PATH} add*)",
      "Bash(git -C {REPO_PATH} commit*)",
      "Bash(git -C {REPO_PATH} push*)",
      "Bash(cd *)",
      "Bash(cat *)",
      "Bash(grep *)",
      "Bash(ls *)",
      "Bash(test *)",
      "Bash(date *)",
      "Bash(echo *)",
      "Bash(head *)",
      "Bash(tail *)",
      "Bash(wc *)",
      "Bash(sort *)",
      "Bash(uniq *)",
      "Bash(cut *)",
      "Bash(awk *)",
      "Bash(sed *)",
      "Bash(tr *)",
      "Bash(printf *)",
      "Bash(find *)",
      "Bash(pwd*)",
      "Bash(which *)",
      "Bash(command *)",
      "Bash(basename *)",
      "Bash(dirname *)",
      "Bash(jq *)",
      "Bash(diff *)",
      "Bash(type *)",
      "Bash(MARKER=*)",
      "Bash(INSTALLED=*)",
      "Bash(AVAILABLE=*)",
      "Bash(date +%s*)"
    ]
  }
}
